"""empty message

Revision ID: 14231c37eea6
Revises: 28b5d6cbea0a
Create Date: 2024-07-13 18:49:56.800006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14231c37eea6'
down_revision = '28b5d6cbea0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
