"""empty message

Revision ID: 28b5d6cbea0a
Revises: 9e9d1fba52be
Create Date: 2024-07-13 17:36:42.642598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b5d6cbea0a'
down_revision = '9e9d1fba52be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('eventName', sa.VARCHAR(length=100), nullable=False),
    sa.Column('eventDate', sa.DATE(), nullable=False),
    sa.Column('eventLocation', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
