"""empty message

Revision ID: 9e9d1fba52be
Revises: 217b8ac273cf
Create Date: 2024-07-13 17:14:33.462665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9d1fba52be'
down_revision = '217b8ac273cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_signup')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventName', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('eventDate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('eventLocation', sa.String(length=255), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('description')
        batch_op.drop_column('location')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('eventLocation')
        batch_op.drop_column('eventDate')
        batch_op.drop_column('eventName')

    op.create_table('event_signup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
